# build only master branch on commit's
# all other branches build on PullRequest creation
branches:
  only:
    - master

language: rust

rust:
# build nightly only for the time beeing
  - nightly

# increase build speed by caching installed cargo dependencies
cache: cargo

# define the stages and their order
stages:
  - unittest

jobs:
  include:
    - stage: unittest
      name: "Compile and UnittestThe Crate"
      install:
        - sudo apt update
        - sudo apt-cache madison qemu
        - sudo apt-cache policy qemu
        #- sudo apt install qemu-kvm
        - sudo apt-get install qemu
        #- sudo apt-get install qemu-system-arm
        - sudo apt-get install -y gcc-aarch64-linux-gnu
        - cargo install cargo-xbuild
        - cargo install cargo-make
        - rustup target add aarch64-unknown-none
        - rustup component add rust-src
        - rustup component add llvm-tools-preview
        # if we not build a PR we remove the patch of the dependencies to their github repo's
        - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then sed -i "/\[patch\.crates-io\]/,$ s/ruspiro-\(.*\)/# ruspiro-\1/g" Cargo.toml; fi'
        # adjust the config.toml to call the test runner with the travis profile
        - sed -i 's/\(cargo make qemu-test\)/\1 --profile travis/g' .cargo/config.toml
      script: cargo make --profile travis unittest
