#***********************************************************************************************************************
# cargo make tasks to build the example for the Raspberry Pi
#***********************************************************************************************************************

# AARCH64 specific profile environment varialbles
[env.development]
CC = "aarch64-none-elf-gcc"
AR = "aarch64-none-elf-ar"
OCOPY = "aarch64-none-elf-objcopy"
CFLAGS = "-march=armv8-a -Wall -O3 -nostdlib -nostartfiles -ffreestanding -mtune=cortex-a53"
RUSTFLAGS = "-C linker=${CC} -C target-cpu=cortex-a53 -C link-arg=-nostartfiles -C link-arg=-T./link64.ld"
BUILD_TARGET = "aarch64-unknown-none"
QEMUMACHINE = "raspi3"

# AARCH64 specific Travis CI env. variables. "aarch64-none-elf" is not available there as it seems
[env.travis]
CC = "aarch64-linux-gnu-gcc"
AR = "aarch64-linux-gnu-ar"
OCOPY = "aarch64-linux-gnu-objcopy"
CFLAGS = "-march=armv8-a -Wall -O3 -nostdlib -nostartfiles -ffreestanding -mtune=cortex-a53"
RUSTFLAGS = "-C linker=${CC} -C target-cpu=cortex-a53 -C link-arg=-nostartfiles -C link-arg=-T./link64.ld"
BUILD_TARGET = "aarch64-unknown-none"
QEMUMACHINE = "raspi3b"

[tasks.unittest]
env = { FEATURES = "ruspiro_pi3" }
command = "cargo"
args = ["xtest", "--target", "${BUILD_TARGET}", "--tests", "--features", "${FEATURES}"]

[tasks.qemu-test-objcopy]
command = "${OCOPY}"
args = ["-O",  "binary",  "${CARGO_MAKE_TASK_ARGS}", "./target/kernel-test.img"]

[tasks.qemu-test]
command = "qemu-system-aarch64"
args = [
    "-semihosting", "-display", "none", "-M", "${QEMUMACHINE}", "-kernel", "./target/kernel-test.img", "-serial", "null", "-serial", "stdio", "-d", "int,mmu", "-D", "qemu-test.log"
]
dependencies = [
    "qemu-test-objcopy"
]